DROP TABLE IF EXISTS shopping_list;
DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name TEXT NOT NULL,
  price DECIMAL(2) NOT NULL,
  checked BOOLEAN DEFAULT FALSE NOT NULL,
  category grocery NOT NULL,
  date_added TIMESTAMPTZ DEFAULT now() NOT NULL
);